#!/usr/bin/env bash

# Function to get DNS record
get_dns_record() {
  local domain=\$1
  local subdomain=\$2
  dig +short ${subdomain}.${domain}
}

# Main script
domain=\$1
subdomain=\$2

subdomains=("www" "lb-01" "web-01" "web-02")

if [ -z "$subdomain" ]; then
  # If no subdomain is specified, display information for all subdomains
  for sub in "${subdomains[@]}"; do
    echo "The subdomain ${sub} is an A record and points to $(get_dns_record $domain $sub)"
  done
else
  # If a subdomain is specified, display information for that subdomain only
  echo "The subdomain ${subdomain} is an A record and points to $(get_dns_record $domain $subdomain)"
fi
