#!/usr/bin/env bash
# Configure a new Nginx server so that /redirect_me is redirecting to another page.

#!/usr/bin/env bash
# Configure a new Nginx server to have a custom 404 page.

# Update and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Create the custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure Nginx for custom 404 error page
new_string="error_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"

sudo sed -i "/error_page 404 /a $new_string" /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
