#!/usr/bin/env bash
# Automating nginx configuration

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'

# adding the custom header
sudo sed -i "/http {/a\         add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf

sudo service nginx restart

# Install nginx on my web-01 web server

# apt-get update
# apt-get -y install nginx
# ufw allow 'Nginx HTTP'
# echo "Hello World!" > /var/www/html/index.nginx-debian.html
# service nginx start
