#!/usr/bin/env bash
# Configure HAProxy load balancer server

apt-get -y update
apt-get -y install haproxy
echo "frontend http
        bind *:80
        mode http
        default_backend web_backend
    backend web_backend
        balance roundrobin
        server 251668-web-01 100.25.133.244:80 check
        server 251668-web-02 100.26.132.163:80 check " >> /etc/haproxy/haproxy.cfg

service haproxy restart
