#!/usr/bin/env bash
#a Bash script that loops from 1 to 10 and  isplays bad luck for the 4th loop iteration, displays good luck for the 8th loop iteration.

i=1
while [ $i -lt 11 ]
do
    if [ $i == 4 ]
    then
        echo "bad luck"
    elif [ $i == 8 ]
    then
        echo "good luck"
    else 
        echo "Best School"
    fi
    ((i++))
done