#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server
# "$2" = The IP of the server we want to transfer the file to
# "$3" = The username scp connects with
# "$4" = The path to the SSH private key that scp uses

if [ $# -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
else
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/$1"
fi
